apiVersion: v1
kind: Pod
metadata:
  name: db-pod
spec:
  containers:
  - name: mysql
    image: mysql:5.7
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: db-vol
  volumes:
  - name: db-vol
    # mount /data/foo, but only if that directory already exists
    hostPath:
      path: /data # directory location on host
      type: DirectoryOrCreate # this field is optional
