apiVersion: v1
kind: Service
metadata:
  name: service-node
spec:
  selector:
    app: app-container-pod
  type: NodePort
  ports:
  - name: service-pod-port
    port: 8090
    nodePort: 30001
    targetPort: app-port
    protocol: TCP

